#!/usr/bin/env bash
# Install ngnix into my server
# Nginx should be listening on port 80
# curl localhost should result "Hello World!"


# Update apt and Install nginx
sudo apt -y update
sudo apt -y install nginx

# Remove and replace /var/www to store static content

rm -rf school
mkdir school
touch school/index.html
echo "Hello World!" > school/index.html
sudo rm -rf /var/www/school
sudo mv school /var/www/

# Change the default configuration of nginx
touch default
printf %s "server {
       listen 80;
       listen [::]:80;

       root /var/www/school;
       index index.html;
}
" > default

# Remove and replace existing configurations
sudo rm -rf /etc/nginx/sites-available/default
sudo rm -rf /etc/nginx/sites-enabled/default
sudo mv default /etc/nginx/sites-available/
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
sudo service nginx restart
